name: 'secrets-inherit'
on: workflow_dispatch

permissions:
  contents: read

jobs:
  secrets-inherit:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Test"
        run: echo "Test"
      - name: 'Running Reusable Workflow'
        uses: test-organization-wengonn-v2/reusable-workflow/.github/workflows/echo-secrets.yml@main
        with:
          secrets: inherit
